---
title: "Extreme Climate Variables"
author: "Kiri Daust"
format: html
editor: source
---

## Load Data

```{r}
library(climr)
library(data.table)
library(ggplot2)
require(tidyverse)

# pnts <- data.table(lon = c(-121.20225,-126.39689,-117.97568,-127.29956,-127.12704,-118.7898,-123.45617,-123.37194), lat = c(50.77239,54.73596,50.28127,50.28127,54.83288,50.24118,48.79616,52.49457), elev = c(588,985,1067,55,563,799,306,1103), id = c("BGxh1","SBSmc2","ICHmw2","CWHvm1","SBSdk","ICHxm1","CDFmm","SBPSdc"))
pnts <- fread("D:/OneDrive - Government of BC/WNA_BGC - Future Forest Ecosystems Centre/WNA_v13_200_rndpts_15Nov.csv")
pnts <- pnts |> rename(lon = xcoord, lat = ycoord, elev = Elev1, id = BGC ) %>% 
  group_by(id) %>% slice(1)

```

## Downscale

```{r}
res <- downscale(pnts, which_refmap = "refmap_climr", 
                 obs_years = 1961:1990, 
                 obs_ts_dataset = "cru.gpcc", 
                 vars = list_vars()) #vars = list_vars("Monthly")[grep("CMD|PPT|Tmax",list_vars("Monthly"))]

res <- res[!is.na(DATASET),]

```

## Statistics for Bioclim Vars

```{r}
bio_vars <- c("MAT","MWMT","MCMT","TD","MAP","MSP","AHM","SHM","DDsub0","DD5","DDsub18","DD18",
              "NFFD","FFP","bFFP","eFFP","PAS","EMT","EXT","Eref","CMD","RH","CMI",
              "Tmax_at", "Tmax_sm", "Tmax_sp", "Tmax_wt", 
              "Tmin_at", "Tmin_sm", "Tmin_sp", "Tmin_wt",
              "PPT_at", "PPT_sm", "PPT_sp", "PPT_wt")

bio_stats <- res[,lapply(.SD, function(x) quantile(x, c(0.01,0.5,0.99))),
                 .SDcols = bio_vars, 
                 by = .(id)]
bio_stats[,Quantile := rep(c("01","50","99"),nrow(pnts))]
temp <- melt(bio_stats, id.vars = c("id","Quantile"))
bio_stats <- dcast(temp, id ~ variable + Quantile)

```

## CMD Variables

```{Rcpp}
#include <Rcpp.h>
using namespace Rcpp;
using namespace std;

// [[Rcpp::export]]
NumericVector cmd_sum(NumericVector vals, double cutoff){
  NumericVector res = NumericVector(vals.size());
  res[0] = vals[0];
  double prev, tmp;
  for(int i = 1; i < vals.size(); i++){
    prev = res[i-1];
    if(vals[i] < 0){
      if(prev > cutoff){
        prev = cutoff;
      }
    }
    tmp = prev + vals[i];
    if(tmp < 0){
      tmp = 0;
    }
    res[i] = tmp;
  }
  return(res);
}
```

```{r}
# calc_cmd <- function(vals){
#   res <- numeric(length(vals))
#   res[1] <- vals[1]
#   for(i in 2:length(vals)){
#     prev <- res[i-1]
#     if(vals[i] < 0){
#       if(prev > 500) prev <- 500
#     }
#     tmp <- prev + vals[i]
#     if(tmp < 0) tmp <- 0
#     res[i] <- tmp
#   }
#   return(res)
# }
```

```{r}
res <- downscale(pnts, which_refmap = "refmap_climr", 
                 obs_years = 1961:1990, 
                 obs_ts_dataset = "cru.gpcc", 
                 vars = list_vars("Monthly")[grep("CMD|PPT|Tmax",list_vars("Monthly"))]) #
res <- res[!is.na(DATASET),]
res2 <- melt(res, id.vars = c("id","DATASET","PERIOD"))
res2[,c("Var","Month") := tstrsplit(variable,"_")]
res2[,Month := as.numeric(Month)]
res_precip <- res2[Var == "PPT" & Month %in% c(10,11,12,1,2,3),.(id,PERIOD,Month,value)]
setorder(res_precip, id, PERIOD, Month)
precip_recharge <- res_precip[,.(precip_sum = sum(value)), by = .(id,PERIOD)]
precip_recharge[,Month := 3]

cmd_res <- res2[Var == "CMD",.(id,PERIOD,Var,Month,value)]
setorder(cmd_res, id, PERIOD, Month)
cmd_res[precip_recharge, precip_sum := precip_sum, on = c("id","PERIOD","Month")]
cmd_res[!is.na(precip_sum),value := value - precip_sum]
cmd_res[,cmd_sum := cmd_sum(value, cutoff = 500), by = .(id)]

cmd_res[,Date := as.Date(paste0(PERIOD,"-",Month,"-01"))]

```

## Plot CMD Sum

```{r heatdrought, fig.cap = "Heat drought events for each site."}
#| label: fig-heatdrought
#| fig-cap: "CMD heat sum and heat drought events"
#| fig-height: 12
#| warning: false
t_res <- res2[Var == "Tmax",.(id,PERIOD,Var,Month,value)]
setorder(t_res, id, PERIOD, Month)
cmd_res[t_res, tmax := i.value, on = c("id","PERIOD","Month")]

cmd.temp <- cmd_res %>% filter(grepl("IDFx", id))
temp <- cmd_res[cmd_sum > 800 & tmax > 30,] %>% filter(grepl("IDFx", id))

ggplot(cmd.temp, aes(x = Date, y = cmd_sum)) +
  geom_line() +
  geom_point(data = temp, color = "red", size = 3)+
  facet_wrap(~id, ncol = 4)
```

## Normal Period Variables

```{r}
##yearly CMD_sum max
cmd_max_ann <- cmd_res[,.(CMD_Max = max(cmd_sum)), by = .(id, PERIOD)]

##three year rolling sum of cmd max
cmd_max_ann[,CMD_3yr := frollsum(CMD_Max, n = 3), by = .(id)] ## maximum value

## number of months with drought
cmd_grow <- cmd_res %>% filter(Month %in% c(4:9))
cmd_drought_md <- cmd_grow[cmd_sum > 600, .(CMD_Drought_MD = .N), by = .(id)]
cmd_drought_vd <- cmd_grow[cmd_sum > 800, .(CMD_Drought_VD = .N), by = .(id)]
cmd_drought_ed <- cmd_grow[cmd_sum > 1000, .(CMD_Drought_ED = .N), by = .(id)]
cmd_drought_xd <- cmd_grow[cmd_sum > 1200, .(CMD_Drought_XD = .N), by = .(id)]

##number of months with heat drought
hdr_md_25 <- cmd_res[cmd_sum > 600 & tmax > 25, .(HDR_25 = .N), by = .(id)]
hdr_md_30 <- cmd_res[cmd_sum > 600 & tmax > 30, .(HDR_30 = .N), by = .(id)]
hdr_md_35 <- cmd_res[cmd_sum > 600 & tmax > 35, .(HDR_35 = .N), by = .(id)]

##number of months with heat drought
hdr_ed_25 <- cmd_res[cmd_sum > 1000 & tmax > 25, .(HDR_25 = .N), by = .(id)]
hdr_ed_30 <- cmd_res[cmd_sum > 1000 & tmax > 30, .(HDR_30 = .N), by = .(id)]
hdr_ed_35 <- cmd_res[cmd_sum > 1000 & tmax > 35, .(HDR_35 = .N), by = .(id)]
##normal period CMD_sum statistics
cmd_max_nrm <- cmd_max_ann[,.(CMD_Max_01 = quantile(CMD_Max,0.01),
                              CMD_Max_5 = quantile(CMD_Max,0.5),
                              CMD_Max_99 = quantile(CMD_Max,0.99)),
                           by = .(id)]
cmd_3yr <- cmd_max_ann[,.(CMD_Max3yr = max(CMD_3yr, na.rm = T)), by = .(id)]
all_normal <- merge(bio_stats, cmd_max_nrm, by = "id", all = T)
all_normal <- merge(all_normal, hdr_md_25, by = "id",all = T)
all_normal <- merge(all_normal, hdr_md_30, by = "id", all = T)
all_normal <- merge(all_normal, hdr_md_35, by = "id", all = T)

all_normal <- merge(all_normal, hdr_ed_25, by = "id",all = T)
all_normal <- merge(all_normal, hdr_ed_30, by = "id", all = T)
all_normal <- merge(all_normal, hdr_ed_35, by = "id", all = T)



all_normal <- merge(all_normal, cmd_drought_md, by = "id", all = T)
all_normal <- merge(all_normal, cmd_drought_vd, by = "id", all = T)
all_normal <- merge(all_normal, cmd_drought_ed, by = "id", all = T)
all_normal <- merge(all_normal, cmd_drought_xd, by = "id", all = T)
#setnafill(all_normal, fill = 0, cols = names(all_normal[-1]))

all_normal[is.na(all_normal)] <- 0
all_normal <- all_normal %>% mutate(zone = str_extract(id, "([:A-Z]+)"))
```

```{r ggplot of drought events}
#| label: fig-md_droughtmonths
#| fig-cap: "Months of moderate drought by Zone"
#| fig-width: 8
#| fig-height: 12
#| out-width: 8in
#| out-height: 12in

reduced_normal <- all_normal %>% filter(zone %in% c("IDF", "ICH","PP","MS","BG","SBPS", "GBD"))

ggplot(reduced_normal, aes(x = id, y = CMD_Drought_MD, fill = zone)) +
  geom_col() +
   facet_wrap(~zone, scales = "free_x", ncol=3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r ggplot of drought events}
#| label: fig-ex_droughtmonths
#| fig-cap: "Months of excessive drought by Zone"
#| fig-width: 8
#| fig-height: 12
#| out-width: 8in
#| out-height: 12in

reduced_normal <- all_normal %>% filter(zone %in% c("IDF", "ICH","PP","MS","BG","SBPS", "GBD"))
ggplot(reduced_normal, aes(x = id, y = CMD_Drought_ED, fill = zone)) +
  geom_col() +
   facet_wrap(~zone, scales = "free_x", ncol=2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r  func1, echo = FALSE}

make_extreme_vars <- function(pnts){
  bio_vars <- c("MAT","MWMT","MCMT","TD","MAP","MSP","AHM","SHM","DDsub0","DD5","DDsub18","DD18",
              "NFFD","FFP","bFFP","eFFP","PAS","EMT","EXT","Eref","CMD","RH","CMI",
              "Tmax_at", "Tmax_sm", "Tmax_sp", "Tmax_wt", 
              "Tmin_at", "Tmin_sm", "Tmin_sp", "Tmin_wt",
              "PPT_at", "PPT_sm", "PPT_sp", "PPT_wt")
  cmd_vars <- list_vars("Monthly")[grep("CMD|PPT|Tmax",list_vars("Monthly"))]
  res <- downscale(pnts, which_refmap = "refmap_climr", 
                 obs_years = 1961:1990, 
                 obs_ts_dataset = "cru.gpcc", 
                 vars = c(bio_vars, cmd_vars))
  res <- res[!is.na(DATASET),]
  
  ##quantiles
  bio_stats <- res[,lapply(.SD, function(x) quantile(x, c(0.01,0.5,0.99))),
                 .SDcols = bio_vars, 
                 by = .(id)]
  bio_stats[,Quantile := rep(c("01","50","99"),nrow(pnts))]
  temp <- melt(bio_stats, id.vars = c("id","Quantile"))
  bio_stats <- dcast(temp, id ~ variable + Quantile)
  
  ##CMD vars
  vars_tmp <- c("id","DATASET","PERIOD",cmd_vars)
  res2 <- res[,..vars_tmp]
  res2 <- melt(res2, id.vars = c("id","DATASET","PERIOD"))
  res2[,c("Var","Month") := tstrsplit(variable,"_")]
  res2[,Month := as.numeric(Month)]
  res_precip <- res2[Var == "PPT" & Month %in% c(10,11,12,1,2,3),.(id,PERIOD,Month,value)]
  setorder(res_precip, id, PERIOD, Month)
  precip_recharge <- res_precip[,.(precip_sum = sum(value)), by = .(id,PERIOD)]
  precip_recharge[,Month := 3]
  
  cmd_res <- res2[Var == "CMD",.(id,PERIOD,Var,Month,value)]
  setorder(cmd_res, id, PERIOD, Month)
  cmd_res[precip_recharge, precip_sum := precip_sum, on = c("id","PERIOD","Month")]
  cmd_res[!is.na(precip_sum),value := value - precip_sum]
  cmd_res[,cmd_sum := cmd_sum(value, cutoff = 500), by = .(id)] ##this line uses the C++ function
  
  cmd_res[,Date := as.Date(paste0(PERIOD,"-",Month,"-01"))]
  t_res <- res2[Var == "Tmax",.(id,PERIOD,Var,Month,value)]
  setorder(t_res, id, PERIOD, Month)
  cmd_res[t_res, tmax := i.value, on = c("id","PERIOD","Month")]
  
  ##summarise variables
  ##yearly CMD_sum max
  cmd_max_ann <- cmd_res[,.(CMD_Max = max(cmd_sum)), by = .(id, PERIOD)]
  
  ##three year rolling sum of cmd max
  cmd_max_ann[,CMD_3yr := frollsum(CMD_Max, n = 3), by = .(id)] ## maximum value
  
  ## number of months with drought
cmd_grow <- cmd_res %>% filter(Month %in% c(4:9))
cmd_drought_md <- cmd_grow[cmd_sum > 600, .(CMD_Drought_MD = .N), by = .(id)]
cmd_drought_vd <- cmd_grow[cmd_sum > 800, .(CMD_Drought_VD = .N), by = .(id)]
cmd_drought_ed <- cmd_grow[cmd_sum > 1000, .(CMD_Drought_ED = .N), by = .(id)]
cmd_drought_xd <- cmd_grow[cmd_sum > 1200, .(CMD_Drought_XD = .N), by = .(id)]
  
  ##number of months with heat drought
  hdr_25 <- cmd_res[cmd_sum > 600 & tmax > 25, .(HDR_25 = .N), by = .(id)]
  hdr_30 <- cmd_res[cmd_sum > 600 & tmax > 30, .(HDR_30 = .N), by = .(id)]
  hdr_35 <- cmd_res[cmd_sum > 600 & tmax > 35, .(HDR_35 = .N), by = .(id)]
  
  ##normal period CMD_sum statistics
  cmd_max_nrm <- cmd_max_ann[,.(CMD_Max_01 = quantile(CMD_Max,0.01),
                                CMD_Max_5 = quantile(CMD_Max,0.5),
                                CMD_Max_99 = quantile(CMD_Max,0.99)),
                             by = .(id)]
  cmd_3yr <- cmd_max_ann[,.(CMD_Max3yr = max(CMD_3yr, na.rm = T)), by = .(id)]
  all_normal <- merge(bio_stats, cmd_max_nrm, by = "id", all = T)
  all_normal <- merge(all_normal, hdr_25, by = "id",all = T)
  all_normal <- merge(all_normal, hdr_30, by = "id", all = T)
  all_normal <- merge(all_normal, hdr_35, by = "id", all = T)
  #all_normal <- merge(all_normal, cmd_drought, by = "id", all = T)
  all_normal <- merge(all_normal, cmd_3yr, by = "id", all = T)
  all_normal <- merge(all_normal, cmd_drought_md, by = "id", all = T)
all_normal <- merge(all_normal, cmd_drought_vd, by = "id", all = T)
all_normal <- merge(all_normal, cmd_drought_ed, by = "id", all = T)
all_normal <- merge(all_normal, cmd_drought_xd, by = "id", all = T)
  #setnafill(all_normal, fill = 0, cols = names(all_normal[-1]))
  
  all_normal[is.na(all_normal)] <- 0
  return(all_normal)
}
```

```{r  func2, echo = FALSE}
make_extreme_vars_fut <- function(pnts, period = 2041:2060, gcm = list_gcms()[1]){
  bio_vars <- c("MAT","MWMT","MCMT","TD","MAP","MSP","AHM","SHM","DDsub0","DD5","DDsub18","DD18",
              "NFFD","FFP","bFFP","eFFP","PAS","EMT","EXT","Eref","CMD","RH","CMI",
              "Tmax_at", "Tmax_sm", "Tmax_sp", "Tmax_wt", 
              "Tmin_at", "Tmin_sm", "Tmin_sp", "Tmin_wt",
              "PPT_at", "PPT_sm", "PPT_sp", "PPT_wt")
  cmd_vars <- list_vars("Monthly")[grep("CMD|PPT|Tmax",list_vars("Monthly"))]
  res <- downscale(pnts, which_refmap = "refmap_climr", 
                 gcms = gcm,
                 ssps = list_ssps()[2],
                 gcm_ssp_years = period,
                 max_run = 3L,
                 vars = c(bio_vars, cmd_vars))
  res <- res[!is.na(GCM),][RUN != "ensembleMean",]
  
  ##quantiles
  bio_stats <- res[,lapply(.SD, function(x) quantile(x, c(0.01,0.5,0.99))),
                 .SDcols = bio_vars, 
                 by = .(id, GCM, RUN)]
  bio_stats[,Quantile := rep(c("01","50","99"),nrow(bio_stats)/3)]
  temp <- melt(bio_stats, id.vars = c("id","GCM","RUN", "Quantile"))
  bio_stats <- dcast(temp, id + GCM + RUN ~ variable + Quantile)
  
  ##CMD vars
  vars_tmp <- c("id","GCM","RUN","PERIOD",cmd_vars)
  res2 <- res[,..vars_tmp]
  res2 <- melt(res2, id.vars = c("id","GCM","RUN","PERIOD"))
  res2[,c("Var","Month") := tstrsplit(variable,"_")]
  res2[,Month := as.numeric(Month)]
  res_precip <- res2[Var == "PPT" & Month %in% c(10,11,12,1,2,3),.(id,Month,GCM, RUN,PERIOD,value)]
  setorder(res_precip, id,GCM,RUN,PERIOD, Month)
  precip_recharge <- res_precip[,.(precip_sum = sum(value)), by = .(id,GCM,RUN,PERIOD)]
  precip_recharge[,Month := 3]
  
  cmd_res <- res2[Var == "CMD",.(id,GCM,RUN,PERIOD,Var,Month,value)]
  setorder(cmd_res, id, GCM,RUN,PERIOD, Month)
  cmd_res[precip_recharge, precip_sum := precip_sum, on = c("id","GCM","RUN","PERIOD","Month")]
  cmd_res[!is.na(precip_sum),value := value - precip_sum]
  cmd_res[,cmd_sum := cmd_sum(value, cutoff = 500), by = .(id,GCM,RUN)] ##this line uses the C++ function
  
  cmd_res[,Date := as.Date(paste0(PERIOD,"-",Month,"-01"))]
  t_res <- res2[Var == "Tmax",.(id,GCM,RUN,PERIOD,Var,Month,value)]
  setorder(t_res, id,GCM,RUN, PERIOD, Month)
  cmd_res[t_res, tmax := i.value, on = c("id","GCM","RUN","PERIOD","Month")]
  
  ##summarise variables
  ##yearly CMD_sum max
  cmd_max_ann <- cmd_res[,.(CMD_Max = max(cmd_sum)), by = .(id,GCM,RUN, PERIOD)]
  
  ##three year rolling sum of cmd max
  cmd_max_ann[,CMD_3yr := frollsum(CMD_Max, n = 3), by = .(id,GCM,RUN)] ## maximum value
  
  ## number of months with drought
  cmd_drought <- cmd_res[cmd_sum > 600, .(CMD_Drought = .N), by = .(id,GCM,RUN)]
  
  ##number of months with heat drought
  hdr_25 <- cmd_res[cmd_sum > 600 & tmax > 25, .(HDR_25 = .N), by = .(id,GCM,RUN)]
  hdr_30 <- cmd_res[cmd_sum > 600 & tmax > 30, .(HDR_30 = .N), by = .(id,GCM,RUN)]
  hdr_35 <- cmd_res[cmd_sum > 600 & tmax > 35, .(HDR_35 = .N), by = .(id,GCM,RUN)]
  
  ##normal period CMD_sum statistics
  cmd_max_nrm <- cmd_max_ann[,.(CMD_Max_01 = quantile(CMD_Max,0.01),
                                CMD_Max_5 = quantile(CMD_Max,0.5),
                                CMD_Max_99 = quantile(CMD_Max,0.99)),
                             by = .(id,GCM,RUN)]
  cmd_3yr <- cmd_max_ann[,.(CMD_Max3yr = max(CMD_3yr, na.rm = T)), by = .(id,GCM,RUN)]
  all_normal <- merge(bio_stats, cmd_max_nrm, by = c("id","GCM","RUN"), all = T)
  all_normal <- merge(all_normal, hdr_25, by = c("id","GCM","RUN"),all = T)
  all_normal <- merge(all_normal, hdr_30, by = c("id","GCM","RUN"), all = T)
  all_normal <- merge(all_normal, hdr_35, by = c("id","GCM","RUN"), all = T)
  all_normal <- merge(all_normal, cmd_drought, by = c("id","GCM","RUN"), all = T)
  all_normal <- merge(all_normal, cmd_3yr, by = c("id","GCM","RUN"), all = T)
  #setnafill(all_normal, fill = 0, cols = names(all_normal[-1]))
  
  all_normal[is.na(all_normal)] <- 0
  return(all_normal)
}
```



```{r test, echo = FALSE}}
# dat_fut <- make_extreme_vars_fut(pnts, period = 2041:2060, gcm = list_gcms()[1])
# 
# ```
