// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nearest_haversine_k_cpp
DataFrame nearest_haversine_k_cpp(DataFrame xyz, DataFrame stations, int k);
RcppExport SEXP _climr_nearest_haversine_k_cpp(SEXP xyzSEXP, SEXP stationsSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type stations(stationsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_haversine_k_cpp(xyz, stations, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_climr_nearest_haversine_k_cpp", (DL_FUNC) &_climr_nearest_haversine_k_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_climr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
